#!/bin/sh

remote="$1"
url="$2"

if [[ $url =~ heroku ]] ; then

    hash_name=HEAD_HASH
    hash=$(git rev-parse HEAD)
    echo Setting $hash_name to $hash
    heroku config:set $hash_name=$hash

fi
exit 0
